---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s-config-map.yaml
- k8s-service-account.yaml
- k8s-deployment.yaml
- k8s-network-policies.yaml
- k8s-pod-disruption-budget.yaml
- k8s-service.yaml
- k8s-ingress.yaml
- flux-image-policy.yaml
- flux-image-repository.yaml
